version: "3.7"

services:
    postgres:
        restart: always
        container_name: nsmarket_postgres
        image: postgres:16-alpine
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        volumes:
          - ./var/pg_data:/var/lib/postgresql
        ports:
          - "5432:5432"
    pgadmin:
      restart: always
      container_name: nsmarket_pgadmin
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=noemail@noemail.com
        - PGADMIN_DEFAULT_PASSWORD=root
      ports:
        - "5050:80"

    # node:
    #     container_name: nsmarket_node
    #     image: node:20-alpine
    #     command: 'sh -c "while true; do sleep 2; done"'
    #     env_file: ./.env
    #     ports:
    #       - "127.0.0.1:3000"
    #     working_dir: /app
    #     volumes:
    #       - ./app:/app
    #       - ./uploads:/uploads